Update Boost to 1.87.0
freeorion/freeorion-sdk pull request #126
Opened 2024-12-28 06:43 UTC by o01eg

2024-12-28 09:05 UTC, o01eg commented
Test build https://github.com/o01eg/freeorion/actions/runs/12525177244/job/34936467814 have same error with MSVS project as previous version.

2024-12-28 16:01 UTC, geoffthemedio commented
works with https://github.com/freeorion/freeorion/tree/sdk_compat

2024-12-29 12:31 UTC, o01eg commented
If it works on MacOS, maybe also release it's as 15th SDK release? @Vezzra @geoffthemedio

2024-12-29 14:16 UTC, Vezzra requested changes
Can build the SDK, can build FO, but FO crashes on startup dumping this to the console:
```
$ ./FreeOrion
dyld[12619]: Library not loaded: '@rpath/libboost_random.dylib'
  Referenced from: '/Volumes/FreeOrion/FreeOrion.app/Contents/SharedSupport/libboost_iostreams.dylib'
  Reason: tried: '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_random.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_random.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../Frameworks/libboost_random.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_random.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../Frameworks/libboost_random.dylib' (no such file), '/usr/local/lib/libboost_random.dylib' (no such file), '/usr/lib/libboost_random.dylib' (no such file)Library not loaded: '@rpath/libboost_graph.dylib'
  Referenced from: '/Volumes/FreeOrion/FreeOrion.app/Contents/SharedSupport/libboost_python39.dylib'
  Reason: tried: '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_graph.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_graph.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../Frameworks/libboost_graph.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libboost_graph.dylib' (no such file), '/Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../Frameworks/libboost_graph.dylib' (no such file), '/usr/local/lib/libboost_graph.dylib' (no such file), '/usr/lib/libboost_graph.dylib' (no such file)
Abort trap: 6
```

2024-12-29 14:19 UTC, Vezzra commented
> If it works on MacOS, maybe also release it's as 15th SDK release? @Vezzra @geoffthemedio

Once it works on Mac, sure, why not.

2024-12-29 14:22 UTC, o01eg commented
I suppose it should be fixed with 

```cmake
        COMMAND
           ${CMAKE_COMMAND} -E copy_if_different "${Boost_RANDOM_LIBRARY}" "$<TARGET_FILE_DIR:freeorion>/../SharedSupport"
        COMMAND
           ${CMAKE_COMMAND} -E copy_if_different "${Boost_GRAPH_LIBRARY}" "$<TARGET_FILE_DIR:freeorion>/../SharedSupport"
```

in CMakeLists.txt in FreeOrion

2024-12-29 17:41 UTC, Vezzra commented
Ok, this is getting odd. When I add these lines to `CMakeLists.txt`, building FO fails with this error in the build log:
```
PhaseScriptExecution CMake\ PostBuild\ Rules /Users/user/SoftwareProjekte/FO/main/build/FreeOrion.build/Release/freeorion.build/Script-91AD46CA2CDFF15F2E45B2CB.sh (in target 'freeorion' from project 'FreeOrion')
    cd /Users/user/SoftwareProjekte/FO/main/src
    /bin/sh -c /Users/user/SoftwareProjekte/FO/main/build/FreeOrion.build/Release/freeorion.build/Script-91AD46CA2CDFF15F2E45B2CB.sh
CMake Error: cmake version 3.24.2
Usage: /Applications/CMake.app/Contents/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  cat [--] <files>...       - concat the files and print them to the standard output
  chdir dir cmd [args...]   - run command in a given directory
  compare_files [--ignore-eol] file1 file2
                              - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME ...] [NAME=VALUE ...] [--] <command> [<arg>...]
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it (deprecated: use rm instead)
  remove_directory <dir>... - remove directories and their contents (deprecated: use rm instead)
  rename oldname newname    - rename a file or directory (on one volume)
  rm [-rRf] [--] <file/dir>... - remove files or directories, use -f to force it, r or R to remove directories and their contents recursively
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch <file>...           - touch a <file>.
  touch_nocreate <file>...  - touch a <file> but do not create it.
  create_symlink old new    - create a symbolic link new -> old
  create_hardlink old new   - create a hard link new -> old
  true                      - do nothing with an exit code of 0
  false                     - do nothing with an exit code of 1

Command PhaseScriptExecution failed with a nonzero exit code
```
However, FO still gets created correctly, but crashes on startup with this output to the console:
```
$ ./FreeOrion
dyld[16272]: Library not loaded: '@rpath/Ogg.framework/Versions/1.3.2/Ogg'
  Referenced from: '/Volumes/FreeOrion 1/FreeOrion.app/Contents/MacOS/FreeOrion'
  Reason: tried: '/Volumes/FreeOrion 1/FreeOrion.app/Contents/MacOS/../SharedSupport/Ogg.framework/Versions/1.3.2/Ogg' (no such file), '/Volumes/FreeOrion 1/FreeOrion.app/Contents/MacOS/../Frameworks/Ogg.framework/Versions/1.3.2/Ogg' (no such file), '/Volumes/FreeOrion 1/FreeOrion.app/Contents/MacOS/../SharedSupport/Ogg.framework/Versions/1.3.2/Ogg' (no such file), '/Volumes/FreeOrion 1/FreeOrion.app/Contents/MacOS/../Frameworks/Ogg.framework/Versions/1.3.2/Ogg' (no such file), '/Library/Frameworks/Ogg.framework/Versions/1.3.2/Ogg' (no such file), '/System/Library/Frameworks/Ogg.framework/Versions/1.3.2/Ogg' (no such file)
Abort trap: 6
```
I'm confused 😕

2024-12-29 18:08 UTC, o01eg commented
@Vezzra I forgot to add those libraries as components. Here is fixed commit https://github.com/o01eg/freeorion/tree/master

2024-12-30 04:49 UTC, o01eg commented
It looks like fixed now on MacOS too https://github.com/o01eg/freeorion/actions/runs/12537393113

2024-12-31 11:40 UTC, Vezzra approved these changes
Ok, I just tried to build commit e9bbf6da9b8dbbb8a8c81c770328e6034700a049 ("Add requirements for Boost.Random and Boost.Graph libraries") of the master branch on your repo, and that worked. I can build and run it.

2024-12-31 11:51 UTC, Vezzra commented
On a second thought, I don't think building that commit pulled the updated SDK. Looks like it used the normal V14 of the SDK, so I probably need to build the SDK manually and check if it works with that commit in your master branch.

2024-12-31 11:59 UTC, Vezzra commented
Ok, sorry, obviously I got confused which commit to use to check/test which issue/PR. Looks like the commit I need to build to check this PR here is https://github.com/o01eg/freeorion/commit/ddc5236aa2c468ac99e5e10a02f6180733fbec8c now, correct?

I'll try that now.

2025-01-01 07:04 UTC, o01eg commented
Oh, I often use `master` to run full tests, correct one is https://github.com/o01eg/freeorion/commit/bf4dda020856818a8b655f01b1a853bb874c6d44

2025-01-01 11:07 UTC, Vezzra commented
Ok, alright, will try that now.

2025-01-01 11:32 UTC, Vezzra commented
Building that commit works, and apparently a new version of the SDK (version 17) gets pulled, so far, so good.

But the app still crashes on startup, this time it's missing `libboost_container.dylib`:
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/libboost_container.dylib'
Referenced from: '/Volumes/VOLUME/FreeOrion.app/Contents/SharedSupport/libboost_python39.dylib'
Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```
Well, at least it's some progress! 😉

2025-01-02 14:23 UTC, o01eg commented
@Vezzra Could you try https://github.com/o01eg/freeorion/commit/cb87a300594baa2ec733d5b2f51ae4694acda3f6 ?

2025-01-02 20:12 UTC, Vezzra commented
> @Vezzra Could you try [o01eg/freeorion@cb87a30](https://github.com/o01eg/freeorion/commit/cb87a300594baa2ec733d5b2f51ae4694acda3f6) ?

Yep, now it works. I can build and run that commit successfully. Looks good!

2025-01-02 23:08 UTC, merged